### ISSUE TITLE
Warning and error message from executing gamma and wilcoxon tests respectively

### ISSUE THREAD

**Issue by BKGiwa** [TeamMacLean/pepdiff#3]
- Selecting a test
=> Unable to conduct two tests among the multiple tests. The tests in question are gamma and wilcoxon:
* Gamma resulted in an error indicating the production of NaNs.
* Wilcoxon resulted in an error stating the absence of the object "wcox."

- Comparing power and effect size
=> No dots (points) appear on the volcano plot when plotting for Cohen's D using the code 'plot_power_volcano(cytosol_results, which = "cohens_d").'

**Comment by danmaclean** [comment]
Hi Tife,

Thanks for raising this, but this isn't an actionable description. Can you provide a minimal example of how these things fail. Also it looks like these might be two separate issues, could you separate out and provide the reprex example for each.

Thanks
Dan

**Comment by BKGiwa** [comment]
The problem occurred under the "selecting a test" section.  I was unable to conduct two statistical tests among the  multiple tests. The tests in question are gamma and wilcoxon. 

Required package:
```
library(pepdiff)
```

Load raw data:

```
example_data <- import_data(
here::here("raw", "reprex_frank.csv"),
gene_id = "protein_name",
treatment = "genotype",
seconds = "timepoints",
peptide = "new_annot",
bio_rep = "bio_rep",
tech_rep = "tech_rep",
quant = "timepoints_values"
)
```

Set up comparisons:

```
comparisons <- data.frame(
  control = rep("Ws", 4),
  c_seconds = rep(0, 4),
  treatment = rep("Ws", 4),
  t_seconds = c(0,150,300,600)
)

comparisons
```

=> For "wilcoxon" test

Code snippet (where the problem lies):
```
example_results_all <- compare_many(example_data, comparisons, tests = c("bootstrap_t", "rank_product", "eb", "kruskal-wallis", "norm_quantile", "wilcoxon"))
```

Expected behaviour:
I was expecting the code to execute without issues, allowing me to visualise the results. Also, I was expecting the output from running this code to be "New names:"

Actual behaviour:
I got the following error message:
"Error in get_wilcoxon_percentile(treatment, control) : 
  object 'wcox' not found"



=> For "gamma" test

Code snippet (where the problem lies):
```
example_results_all <- compare_many(example_data, comparisons, tests = c("bootstrap_t", "rank_product", "eb", "kruskal-wallis", "norm_quantile", "gamma"))
```

Expected behaviour:
I was expecting the code to execute without issues, allowing me to visualise the results. Also, I was expecting the output from running this code to be "New names:"

Actual behaviour:
I got the following warning message:
"Warning: NaNs produced"

Note: Although I managed to view the results of the gamma tests without any problems, the issue arises from an extensive warning message that gets printed out. This extended length might not be an issue when using the smaller dummy dataset I created, as it typically results in only about one line being printed.

The link to the dummy data:
[reprex_frank.csv](https://github.com/TeamMacLean/pepdiff/files/13952287/reprex_frank.csv)

**Comment by danmaclean** [comment]
Hi Tife thanks for this. I note you raise two issues here, they should really be in separate descriptions.

For the first one, the wilcoxon, the fix is in at https://github.com/TeamMacLean/pepdiff/commit/5b6418a03d737d179c56059dfb0cb722bbb8bff0

For the second on, the gamma, there isn't actually an issue. The NaNs are correct. The test doesn't work on the data you have, so it generates NaN and it's appropriate to warn you. Its the job of the user to deal with the output in this case.
