### ISSUE TITLE
Missing data points on volcano plot for Cohen's D analysis

### ISSUE THREAD

**Issue by BKGiwa** [TeamMacLean/pepdiff#4]
The problem occurred under the "comparing power and effect size" section. No dots ( data points) appear on the volcano plot when plotting for Cohen's D analysis.

Required package:
```
library(pepdiff)
```

Load raw data:
```
example_data <- import_data(
here::here("raw", "reprex_frank.csv"),
gene_id = "protein_name",
treatment = "genotype",
seconds = "timepoints",
peptide = "new_annot",
bio_rep = "bio_rep",
tech_rep = "tech_rep",
quant = "timepoints_values"
)
```

Set up comparisons:
```
comparisons <- data.frame(
  control = rep("Ws", 4),
  c_seconds = rep(0, 4),
  treatment = rep("Ws", 4),
  t_seconds = c(0,150,300,600)
)

comparisons
```

Perform bootstrap t-test 
```
example_results <- compare_many(example_data, comparisons, tests = c("bootstrap_t") ) 
```

Code snippet (where the problem lies):
```
plot_power_volcano(example_results, which = "cohens_d")
```

Expected behaviour:
I expected that the data points would be displayed on the volcano plot, highlighting the peptides with sufficient statistical power and those that are underpowered.

Actual behaviour:
Contrary to expectation, no data points (dots) were shown on the volcano plot

The link to the dummy data:
[reprex_frank.csv](https://github.com/TeamMacLean/pepdiff/files/13952287/reprex_frank.csv)

**Comment by danmaclean** [comment]
Hi Tife.

Thanks for this, this should now be fixed under https://github.com/TeamMacLean/pepdiff/commit/d07581369ebd7d6fb776caca7c1e724716931887
